### ISSUE TITLE
Problem after scan long barcode and after short barcode

### ISSUE THREAD

**Issue by RobertZawadzki** [lhengen/RawInput#1]
Hi,

I have problem when I scanned long barcode (for example 480126581834) and after scanned short barcode (for example 201426053).

After scanned long barcode, variable sMessage is:
'480126581834'#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0...

and after scanned short barcode, variable sMessage is:
'201426053**834**'#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0#0...

'834' is rest of long barcode?

**Comment by lhengen** [comment]
Yes I presume that is the case.  The barcodes I was scanning were of a fixed length.  At line 523 after the call to SendMessage() you could add a call to ZeroMemory to clear the entire buffer or before the SendMessage you could insert a null terminator ( FBarcode[FBarCodeIndex] := #0).  If you want to implement one of those fixes, test and do a pull request that would be great!

**Comment by RobertZawadzki** [comment]
This works perfectly
```
ZeroMemory(@FBarCode, sizeOf(FBarCode));
```

but when I sending barcode to tedit I didn't have enter (#13) code to start events. How repair it?

**Comment by lhengen** [comment]
Sorry I'm not sure what you mean.  If you want to trigger the OnExit event of a TEdit then just set focus to another control.  If you are referring to the scanner not sending a #13 to trigger the SendMessage call, this is usually configurable on the scanner itself.  The default for many is to terminate the barcode with a #13 which is why it was used.  Scanners will often have a "programming page" of codes to scan in order to configure it.  You will have to consult the manual for the scanner you are using.

**Comment by RobertZawadzki** [comment]
Ok, it doesn't matter because I solved this problem. Thank you very much for your solution. You saved my a lot of time

**Comment by lhengen** [comment]
Since I have not received a pull request I have added the ZeroMemory call and pushed the changes.
